### ISSUE TITLE
User Experience Must Have 1

### ISSUE THREAD

**Issue by Bebolor** [WomenPlusPlus/deploy-impact-21-kona-c#98]
1. Targeted simple questions to guide users to be matched (SDGs and location) to the right help by associations.

**Comment by ClaudiaNicolae** [comment]
I think this a duplicate of the current stories that we have in the Sprint. This will be more of an epic. I suggest we close this one.

**Comment by ClaudiaNicolae** [comment]
Done as part of other issues
